name: TacticsCrafter

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name:
          - win64
          - win32
          - macos
        include:
          - name: win64
            os: windows-2019
            qt_arch: win64_msvc2019_64
            cmake_opts: -A x64
          - name: win32
            os: windows-2019
            qt_arch: win32_msvc2019
            cmake_opts: -A Win32
          - name: macos
            os: macos-latest
            cmake_opts: -DCMAKE_BUILD_TYPE=Release
    runs-on: ${{ matrix.os }}
    env:
      QT_VERSION: 5.15.2
    steps:
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: Qt-${{ env.QT_VERSION }}-${{ matrix.name }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: ${{ matrix.qt_arch }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: |
        mkdir build
    - name: Build
      run: |
        cmake .. ${{ matrix.cmake_opts }} -DNIGHTLY=${{ !startsWith(github.ref, 'refs/tags/') }}
        cmake --build . --config Release
      working-directory: ./build
    - name: Package
      run: |
        cmake --build . --config Release --target package
        cmake -E remove_directory ./pkg/_CPack_Packages
      working-directory: ./build
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.name }}
        path: build/pkg
  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: Download win64
        uses: actions/download-artifact@v1
        with:
          name: win64
          path: pkg
      - name: Download win32
        uses: actions/download-artifact@v1
        with:
          name: win32
          path: pkg
      - name: Download macOS
        uses: actions/download-artifact@v1
        with:
          name: macOS
          path: pkg
      - name: Pre Release
        if: startsWith(github.ref, 'refs/heads/master')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            pkg/*
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "pkg/*"
          draft: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
